# Generated by Django 2.2 on 2019-11-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191116_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка'),
        ),
    ]
